-- Seed initial topics for the daily AI-generated "Article" feature.
-- Topics with used_at = NULL have not been used by the generator yet.
INSERT INTO "topic_queue" ("id", "topic", "context", "created_at") VALUES
  (gen_random_uuid(), 'Bagaimana bank menghasilkan uang dari bunga pinjaman?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Kenapa bunga tabungan jauh lebih kecil dari bunga kredit?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa itu bunga majemuk (compound interest) dan kenapa penting?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana bank bisa "menciptakan" uang lewat sistem cadangan minimum (fractional reserve)?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa bedanya bunga flat dan bunga efektif pada cicilan?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana kartu kredit menghasilkan uang untuk bank?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Model bisnis Gojek: dari mana uangnya selain ongkos perjalanan?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana e-commerce seperti Tokopedia/Shopee menghasilkan uang meski ongkir gratis?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana bank digital seperti Jago/SeaBank bisa untung meski tanpa biaya admin?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Model bisnis marketplace: komisi, iklan, dan biaya penitipan barang', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana perusahaan asuransi menghasilkan uang dari premi yang kita bayar?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Model bisnis dompet digital (GoPay, OVO, Dana): dari mana untungnya?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana minimarket seperti Indomaret/Alfamart menghasilkan margin dari tiap produk?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa itu dividen dan bagaimana cara perusahaan membagikannya ke pemegang saham?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa itu obligasi dan bagaimana cara kerja bunga kupon?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa itu royalti dan bagaimana pencipta karya bisa terus dapat uang dari karyanya?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana cara kerja penghasilan afiliasi (affiliate marketing)?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Dari mana uang platform media sosial dari iklan yang kita lihat?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa itu passive income dan contoh nyatanya di Indonesia?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana cara kerja reksa dana dan dari mana untungnya?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa itu inflasi dan kenapa uang kita "menyusut" nilainya tiap tahun?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa itu cash flow dan kenapa penting walau sudah untung di atas kertas?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Kenapa harga emas cenderung naik saat inflasi tinggi?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa bedanya aset dan liabilitas dalam keuangan pribadi?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana cara kerja pajak penghasilan (PPh) di Indonesia secara sederhana?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa itu diversifikasi investasi dan kenapa jangan taruh telur di satu keranjang?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana startup bisa "bakar uang" bertahun-tahun sebelum untung?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa itu equity dan kenapa karyawan startup sering dibayar pakai saham?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Bagaimana cara kerja sistem BI Checking / SLIK OJK terhadap pinjaman kita?', NULL, CURRENT_TIMESTAMP),
  (gen_random_uuid(), 'Apa itu opportunity cost dalam keputusan keuangan sehari-hari?', NULL, CURRENT_TIMESTAMP);
